# Задание 1
Скачайте с сайта https://grouplens.org/datasets/movielens/ датасет любого размера. Определите какому фильму было выставлено больше всего оценок 5.0.

In [77]:
import pandas as pd

data_film = pd.read_csv('ratings.csv')

data_film_best = data_film[data_film.rating == 5]

#print(len(data_film))
#print(len(data_film_best))

data_film_best.groupby('movieId').count().sort_values('userId', ascending=False).head(1)

         userId  rating  timestamp
movieId
318         153     153        153

# Задание 2
По данным файла power.csv посчитайте суммарное потребление стран Прибалтики (Латвия, Литва и Эстония) категорий 4, 12 и 21 за период с 2005 по 2010 года. Не учитывайте в расчетах отрицательные значения quantity.

In [75]:
import pandas as pd

data_power = pd.read_csv('power.csv')
#data_power.head()

data_power_pbaltik = data_power[ (data_power['country']=='Latvia') | (data_power['country']=='Lithuania') | (data_power['country']=='Estonia') ]

data_power_pbaltik_year = data_power_pbaltik[ (data_power_pbaltik['year'] >= 2005) & (data_power_pbaltik['year'] <= 2010)]  

data_power_pbaltik_year_category = data_power_pbaltik_year[(data_power_pbaltik_year['category'] == 4)|(data_power_pbaltik_year['category'] == 12)|(data_power_pbaltik_year['category'] == 21)].sort_values('quantity', ascending=False)

print(data_power_pbaltik_year_category.query('quantity > 0')['quantity'].sum())

240580.0

# Задание 3
Выберите страницу любого сайта с табличными данными. Импортируйте таблицы в pandas dataframe.
Примеры страниц (необязательно брать именно эти): 
https://fortrader.org/quotes
https://www.finanz.ru/valyuty/v-realnom-vremeni

In [95]:
dataframe = pd.read_html('https://fortrader.org/quotes')


dataframe

[                               Type    Last   Chg.  Chg.%  Time
 0  Нефть (BRENT) Курс нефти сегодня  58.620  0.080  0.140   NaN
 1   Нефть (WTI) Цены на нефть (WTI)  54.150  0.260  0.480   NaN
 2          Сахар котировки на сахар  12.630  0.000  0.000   NaN
 3                   Газ Цена на газ   2.211  0.053  2.456   NaN,
                                     Type          Last      Chg.     Chg.%  \
 0                      ВТБ Акции ОАО ВТБ       0.03815  +0.00004   0.10496
 1                 Газпром Акции газпрома     229.72000     +0.40   0.17000
 2                    Лукоил Акции Лукойл    5115.00000     -53.0  -1.00000
 3                Роснефть Акции Роснефти     406.55000     +0.80   0.20000
 4               Сбербанк Акции Сбербанка     218.74000     -1.06  -0.48000
 5   Сургутнефтегаз Акции Сургутнефтегаза      25.59500    -0.010  -0.03900
 6              Норникель Акции Норникель   15396.00000        -4  -0.00000
 7               Аэрофлот Акции Аерофлота     109.30000     +12.5  12.90000
 8            Северсталь Акции Северсталь     948.20000      +4.2   0.40000
 9            Транснефть Акции транснефти  150350.00000   -15 950 -10.00000
 10     Ростелеком Курс акций ростелекома      80.86000     +8.03  11.03000
 11                     RUSAL акции RUSAL       3.07000     -0.09  -2.85000

     Time
 0    NaN
 1    NaN
 2    NaN
 3    NaN
 4    NaN
 5    NaN
 6    NaN
 7    NaN
 8    NaN
 9    NaN
 10   NaN
 11   NaN  ,
                           Type      Last   Chg.    Chg.%  Time
 0      Серебро Цена на серебро    14.987 -2.425 -13.9270   NaN
 1      Платина Цены на платину   857.100 -2.000  -0.2000   NaN
 2    Палладий Цена на палладий  1458.850  9.500   0.6600   NaN
 3      Медь Цена меди на бирже     2.539  0.014   0.5545   NaN
 4  Золото Цена золота на бирже  1530.490  4.220   0.2800   NaN,
                                 Type    Last   Chg.  Chg.%  Time
 0               Яндекс Акции яндекса   36.24   0.51   1.43   NaN
 1          Microsoft Microsoft Corp.  134.86  27.58  25.71   NaN
 2                  APPLE Акции APPLE  205.94   3.98   1.97   NaN
 3                Toyota Акции Тойоты  120.94   0.00   0.00   NaN
 4   Volkswagen Курс акций Volkswagen  144.03  -0.21  -0.15   NaN
 5       Facebook Цена акций Facebook  179.31   1.52   0.85   NaN
 6          Tesla Цены на акции Тесла  213.44   1.96   0.93   NaN
 7          Twiter Цена акций твитера   41.10   0.22   0.54   NaN
 8  Hasbro Цена на акции Hasbro, Inc.  107.31  22.44  26.44   NaN,
                                                 Type       Last      Chg.  \
 0                         EURUSD Курс евро к доллару    1.11087  -0.00410
 1   AUDUSD Курс австралийского доллара к доллару сша    0.71501   0.03991
 2         AUDCAD Australian Dollar / Canadian Dollar    0.95727   0.06039
 3                          EURCHF Euro / Swiss Franc    1.14008   0.05373
 4                  EURGBP Euro / Great Britain Pound    0.90851   0.00041
 5                         EURJPY Euro / Japanese Yen  125.80000   8.36100
 6          GBPJPY Great Britain Pound / Japanese Yen  145.40200  15.88800
 7                        GBPUSD Курс фунта к доллару    1.22251  -0.00423
 8       USDCAD Курс канадского доллара к доллару сша    1.33885   0.01029
 9              NZDUSD New Zealand Dollar / US Dollar    0.66833   0.02903
 10                    USDCHF US Dollar / Swiss Franc    1.01425   0.03950
 11         USDCNH Курс китайского юаня к доллару США    7.16812  -0.00735
 12                        USDJPY Курс йены к доллару  111.93100   6.54500

        Chg.%  Time
 0   -0.36772   NaN
 1    5.91172   NaN
 2    6.73334   NaN
 3    4.94592   NaN
 4    0.04515   NaN
 5    7.11900   NaN
 6   12.26700   NaN
 7   -0.34482   NaN
 8    0.77452   NaN
 9    4.54090   NaN
 10   4.05232   NaN
 11  -0.10243   NaN
 12   6.21100   NaN  ,
                                                  Type           Last  \
 0                               Bitcoin Курс биткоина   10327.500000
 1          Litecoin Курс лайткоин к доллару (LTC/USD)      73.621000
 2   BitcoinCash Курс Биткоин кеш к доллару США (BC...     307.820000
 3                                           Dash Dash      91.360000
 4                                       Ripple Ripple       0.270550
 5                                   Ethereum Ethereum     188.375000
 6                                   EmerCoin EmerCoin       0.140050
 7                                   NameCoin NameCoin       0.274000
 8                                   PeerCoin PeerCoin       1.300000
 9                             BTCRUB биткоин в рублях  247059.000000
 10                              BTCEUR биткоин в евро    9233.320000
 11                                        Zcash (ZEC)      51.998000
 12                                          NEO (NEO)       9.816100
 13                                          EOS (EOS)       3.597000
 14                                         TRON (TRX)       0.017838
 15                                             Monero      81.646000
 16                                            Cardano       0.049800
 17                                               IOTA       0.265180
 18                       ETC/USD эфириум классик, ETC       7.328800

          Chg.      Chg.%  Time
 0    +332.790   3.330000   NaN
 1      +1.527   2.118000   NaN
 2      +7.010   2.330000   NaN
 3      +0.410   0.451000   NaN
 4    +0.00315   1.178010   NaN
 5      +4.240   2.303000   NaN
 6     0.00000   0.000000   NaN
 7      -0.051 -15.692000   NaN
 8       +0.16  14.040000   NaN
 9   -3 097.00  -1.240000   NaN
 10   +308.440   3.456000   NaN
 11     +1.863   3.716000   NaN
 12    +0.1582   1.638000   NaN
 13     +0.049   1.384000   NaN
 14  +0.000334   1.908135   NaN
 15     +1.042   1.293000   NaN
 16     0.0000   0.020100   NaN
 17   -0.00101  -0.379430   NaN
 18    +0.2047   2.873300   NaN  ,
                                        Type       Last    Chg.  Chg.%  Time
 0   Фьючерс РТС Курс фьючерса на индекс РТС  118130.00    0.00   0.00   NaN
 1                      РТС Курс индекса РТС    1271.40    8.05   0.64   NaN
 2                                     DAX30   12270.70  742.50   6.40   NaN
 3                       Индекс Dow 30 (DJI)   25820.00  205.00   1.00   NaN
 4                                      FTSE    7137.70  121.20   1.70   NaN
 5                                    CAC 40    5279.70    0.00   0.00   NaN
 6                                Nasdaq 100    7547.38   59.18   0.79   NaN
 7                              Russell 2000    1594.50    6.20   0.40   NaN
 8                                   S&P 500    2816.30   10.80   0.40   NaN
 9                                   IBEX 35    9595.40  981.70  11.40   NaN
 10                               Nikkei 225   21779.00   39.00   0.00   NaN
 11                            Euro Stoxx 50    3513.20  204.50   6.20   NaN
 12                                  S&P 500    2904.60   57.70   2.00   NaN
 13                              S&P/ASX 200    6288.50 -142.20  -2.20   NaN
 14                                      MIB   20651.00  205.00   1.00   NaN,
                                Type     Last    Chg.   Chg.%  Time
 0  EURRUB Курс евро к рублю сегодня  73.3184 -0.1741 -0.2369   NaN
 1       USDRUB Курс рубля к доллару  66.0104  0.3034  0.4617   NaN]